[project]
name = "quantiloon"
version = "0.1.0"
requires-python = ">=3.11,<3.13"

dependencies = [
  "fastapi==0.111.0",
  "uvicorn[standard]==0.30.1",
  "pydantic==2.8.2",
  "torch==2.3.1",
  "transformers==4.43.2",
  "scikit-learn==1.5.1"
]
